FORMAT: 1A

# Scrutinizer

Scrutinizer is an API aimed at testing a number of key aspects of a website

# Group Tests

Resources related to tests that can be run by the API.

## Sitemap Test [/tests/sitemap]

### Run Sitemap Test [POST]

+ Request (application/json)

    + Body

            {
              "url": "https://example.org"
            }

+ Response 200 (application/json)

        {
            "exists": true,
            "compressed": false
        }

## Robots Text Test [/tests/robotsText]

### Run Robots Text Test [POST]

+ Request (application/json)

    + Body

            {
              "url": "https://example.org"
            }

+ Response 200 (application/json)

        {
            "exists": false,
            "empty": null
        }