FORMAT: 1A

# Scrutinizer

Scrutinizer is an API aimed at testing a number of key aspects of a website

# Group SEO Tests

A group of tests related to SEO

## Sitemap [/tests/seo/sitemap?url={url}]

### Sitemap Test [GET]

+ Parameters
    + url: `https://example.org` (string, required) - URL of the site to test.

+ Response 200 (application/json)

        {
            "problems": [
                "Sitemap could not be found"
            ],
            "warnings": [],
            "notices": [],
            "data": []
        }

## Robots Text [/tests/seo/robotsText?url={url}]

### Robots Text Test [GET]

+ Parameters
    + url: `https://example.org` (string, required) - URL of the site to test.

+ Response 200 (application/json)

        {
            "problems": [
                "Robots text file could not be found"
            ],
            "warnings": [],
            "notices": [],
            "data": []
        }


# Group Performance Tests

A group of tests related to performance

## Response Time [/tests/performance/responseTime?url={url}]

### Response Time Test [GET]

+ Parameters
    + url: `https://example.org` (string, required) - URL of the site to test.

+ Response 200 (application/json)

        {
            "problems": [
                "Site is slow to respond"
            ],
            "warnings": [],
            "notices": [],
            "data": [
                {
                    "responseTime":1.28789
                }
            ]
        }


# Group Security Tests

A group of tests related to security

## SSL Labs [/tests/security/sslLabs?url={url}]

### SSL Labs Test [GET]

+ Parameters
    + url: `https://example.org` (string, required) - URL of the site to test.

+ Response 200 (application/json)

        {
            "problems": [
                "Site has poor SSL configuration"
            ],
            "warnings": [],
            "notices": [],
            "data": [
                {
                    "grade": "D"
                }
            ]
        }
